# ชื่อของ Workflow ที่จะแสดงในแท็บ Actions
name: Crypto Signal Monitor

on:
  # ตั้งเวลาให้รันอัตโนมัติ (Cron Job)
  # Syntax: นาที ชั่วโมง วัน เดือน วันในสัปดาห์ (ใช้เวลา UTC)
  # ตัวอย่างนี้คือ: รันทุกวันที่เวลา 00:10 UTC (ตี 7 โมง 10 นาที เวลาไทย)
  schedule:
    - cron: '0 23 * * *'

  # อนุญาตให้สามารถกดรัน Workflow นี้ได้เองจากหน้าเว็บ GitHub (สำหรับทดสอบ)
  workflow_dispatch:

jobs:
  # ชื่องาน (Job)
  run-monitor:
    # เลือก OS ที่จะใช้รัน (ubuntu-latest เป็นตัวเลือกมาตรฐานและดีที่สุด)
    runs-on: ubuntu-latest

    steps:
      # Step 1: ดึงโค้ดล่าสุดจาก Repository ของคุณมาไว้ใน Runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: ตั้งค่า Python เวอร์ชั่น 3.10 (หรือเวอร์ชั่นอื่นที่ต้องการ)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: ติดตั้ง Dependencies จากไฟล์ requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: รันสคริปต์ Python ของคุณ
      - name: Run CDC Action Zone Monitor
        # --- ส่วนที่อัปเดต ---
        # เพิ่ม env block นี้เพื่อส่งค่า secrets ไปให้ python script
        # สคริปต์จะสามารถใช้ os.getenv() เพื่ออ่านค่าเหล่านี้ได้
        env:
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scan_signal.py # <-- ตรวจสอบให้แน่ใจว่าชื่อไฟล์ถูกต้อง
